import type { Config } from 'tailwindcss'

export default {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#e7deff',
        'primary-fixed-dim': '#cbc1e7',
        'surface-tint': '#615a7a',
        'on-secondary-container': '#616a00',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        'secondary': '#5c6300',
        'on-tertiary-container': '#ea4b46',
        'tertiary': '#000000',
        'surface-container': '#eeeeee',
        'secondary-fixed-dim': '#c1d000',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#ffdad6',
        'error-container': '#ffdad6',
        'surface-container-high': '#e8e8e8',
        'on-tertiary-fixed': '#410003',
        'on-error-container': '#93000a',
        'outline': '#79767e',
        'on-primary-fixed-variant': '#494261',
        'outline-variant': '#cac5ce',
        'surface': '#f9f9f9',
        'on-tertiary-fixed-variant': '#930211',
        'primary-container': '#1d1733',
        'tertiary-fixed-dim': '#ffb3ad',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'inverse-primary': '#cbc1e7',
        'surface-bright': '#f9f9f9',
        'on-primary-container': '#877fa1',
        'on-background': '#1a1c1c',
        'secondary-fixed': '#dcee15',
        'secondary-container': '#dcee15',
        'on-surface-variant': '#48464d',
        'on-secondary-fixed': '#1a1d00',
        'background': '#f9f9f9',
        'surface-container-highest': '#e2e2e2',
        'on-primary-fixed': '#1d1733',
        'tertiary-container': '#410003',
        'on-surface': '#1a1c1c',
        'surface-dim': '#dadada',
        'primary': '#000000',
        'error': '#ba1a1a',
        'surface-variant': '#e2e2e2',
        'on-secondary-fixed-variant': '#454b00',
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'base': '8px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        sans:                ['var(--font-hanken)', 'system-ui', 'sans-serif'],
        syne:                ['var(--font-syne)', 'sans-serif'],
        hanken:              ['var(--font-hanken)', 'sans-serif'],
        'display-lg':        ['var(--font-syne)', 'sans-serif'],
        'display-lg-mobile': ['var(--font-syne)', 'sans-serif'],
        'headline-lg':       ['var(--font-syne)', 'sans-serif'],
        'headline-md':       ['var(--font-syne)', 'sans-serif'],
        'body-lg':           ['var(--font-hanken)', 'sans-serif'],
        'body-md':           ['var(--font-hanken)', 'sans-serif'],
        'label-bold':        ['var(--font-hanken)', 'sans-serif'],
        'label-sm':          ['var(--font-hanken)', 'sans-serif'],
      },
      fontSize: {
        'display-lg':        ['80px',  { lineHeight: '88px',  letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-lg-mobile': ['48px',  { lineHeight: '52px',  letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg':       ['40px',  { lineHeight: '48px',  letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md':       ['32px',  { lineHeight: '40px',  fontWeight: '700' }],
        'body-lg':           ['18px',  { lineHeight: '28px',  fontWeight: '400' }],
        'body-md':           ['16px',  { lineHeight: '24px',  fontWeight: '400' }],
        'label-bold':        ['14px',  { lineHeight: '20px',  letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm':          ['12px',  { lineHeight: '16px',  fontWeight: '500' }],
      },
      keyframes: {
        marquee: {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee 25s linear infinite',
      },
    },
  },
  plugins: [],
} satisfies Config
